### ISSUE TITLE
CZI without channel name cannot be read from aicsimageio / aicspylibczi

### ISSUE THREAD

**Issue by sebi06** [AllenCellModeling/aicspylibczi#108] opened 2022-06-30 15:08 UTC
Hi,
For CZI files it is not mandatory to have a channel name inside the metadata. (I am not sure if the bug entry should be rather in the aicsimagio repo - feel free to move it)

When trying to read such a CZI file:

https://www.dropbox.com/s/245eurxtvs4nu1n/211122_AM_Al2O3_SE_021_sp.czi?dl=0

from inside Napari for exmaple it will fail with here:

```text
File ~\Miniconda3\envs\napari_czmodel\lib\site-packages\aicsimageio\readers\czi_reader.py:471, in CziReader._get_coords_and_physical_px_sizes(xml=<Element 'ImageDocument'>, scene_index=0, dims_shape={'T': (0, 1), 'X': (0, 2048), 'Y': (0, 1536)})
    469 channels = img.findall("./Channel")
    470 for channel in channels:
--> 471     channel_name = channel.attrib["Name"]
        channel = <Element 'Channel' at 0x000000006378A540>
    472     scene_channel_list.append(channel_name)
    474 # Attach channel names to coords

KeyError: 'Name'
```
![image](https://user-images.githubusercontent.com/3833249/176711028-8812b071-377f-4342-bbfd-bbcf171ef298.png)

Idea:

* be more forgiving here (see below)
* if no entry is found look under "DisplaySettings" (see below)

Remark: Inside the metadata there is no attribute "@Name" - this is created when using `xmltodict` to convert the XML to the dictionary.

![image](https://user-images.githubusercontent.com/3833249/176711411-223edaf9-963d-44db-bdd1-804c987ebc52.png)

**Comment by JacksonMaxfield** [comment] 2022-06-30 15:24
This is a duplicate of https://github.com/AllenCellModeling/aicsimageio/issues/279

If you want too make a PR to fix, the general idea is to use our `metadata_utils` module to create a channel name from the scene and channel index.

**Closed by JacksonMaxfield** 2022-06-30 15:24 UTC
